sudo: required
language: generic
dist: bionic
#os: osx

install:
    - sudo apt install cmake g++ gcc
    - git clone --depth 1 https://github.com/google/googletest.git -b release-1.10.0
    - cd googletest        # Main directory of the cloned repository.
    - mkdir build          # Create a directory to hold the build output.
    - cd build
    - cmake ..             # Generate native build scripts for GoogleTest.
    - make
    - sudo make install
    - cd ../../




before_script:
    - mkdir -p build/
    - cd build
    - cmake ..

script:
    - ./UnitTests
