sudo: required
language: generic
dist: bionic

install:
    - git clone --depth 1 https://github.com/google/googletest.git -b release-1.10.0
    - cd googletest        # Main directory of the cloned repository.
    - mkdir build          # Create a directory to hold the build output.
    - cd build
    - cmake ..             # Generate native build scripts for GoogleTest.
    - make
    - make install
    - cd ../../
    - apt install valgrind




before_script:
    - mkdir -p build/
    - cd build
    - cmake ..
    - make

script:
    - ./ManagerUnitTests
    - valgrind --leak-check=full ./ManagerUnitTests
    - cd ../
    - ./check_coverage.sh
